HackathonTeam05/Guardian

package-lock.json, package.json
=> add express and tailwind to dependencies

src/components/Image.tsx
=> feat: add Image component

src/components/Image.tsx
=> update: image component

src/components/Button.tsx
=> update: button component

index.html, src/styles.css, tailwind.config.js
=> fix: configure Tailwind

src/components/Input.tsx
=> feat: create input component

frontend/src/App.tsx, frontend/src/pages/DashboardPage.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/RegisterPage.tsx
=> feat: add routes and pages

frontend/src/App.tsx, frontend/src/components/ThemeToggleButton.tsx, frontend/src/pages/LoginPage.tsx
=> feat: add login page and theme toggle button

frontend/src/App.tsx, frontend/src/pages/LoginPage.tsx
=> feat: add route from login to dashboard on sign in

frontend/src/pages/LoginPage.tsx
=> feat: add route from login to register on sign up

frontend/package-lock.json, frontend/package.json, frontend/src/components/AlertMessage.tsx, frontend/src/stories/AlertMessage.stories.ts
Criado componente de alerta capaz de exibir uma mensagem com titulo, texto princial e texto em destaque.
=> feat: Create alertcomponent and stories

backend/config/database.js, backend/index.js, backend/package-lock.json, backend/package.json, backend/vercel.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Calendar.tsx, frontend/src/stories/Calendar.stories.ts
Criado server com express e rotas de teste #45
=> I#45 Server js in backend

frontend/src/App.tsx, frontend/src/components/Input.tsx, frontend/src/pages/DashboardPage.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/RegisterPage.tsx, frontend/src/stories/Input.stories.ts
=> feat: create register page

backend/src/index.js
#50 Criado rotas de get e banco de dados
=> feat: create database and first datas

frontend/src/components/List.tsx, frontend/src/components/ListItem.tsx, frontend/src/components/RecentActivities.tsx, frontend/src/pages/DashboardPage.tsx
=> feat: list items on recent activities

frontend/src/pages/LoginPage.tsx, frontend/src/pages/RegisterPage.tsx
=> update: login and registration pages

frontend/src/components/ThemeToggleButton.tsx
=> update: theme toggle button

frontend/src/components/Navbar.tsx
=> feat: add home button to navbar

shared/.gitignore, shared/main.js, shared/main.spec.js, shared/package-lock.json, shared/package.json, shared/style.css
#76 Criado arquivos iniciais para teste dentro de uma pasta shared
=> feat: create shared file and first test

backend/src/index.js, backend/src/routes/delete.js, backend/src/routes/get.js, backend/src/routes/post.js, backend/src/routes/put.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/Calendar.tsx, frontend/src/pages/EasyRoomPage.tsx, frontend/src/stories/Calendar.stories.ts
Criado componente de calendario e seu story
=> I#44 Create Calendar component

frontend/src/App.tsx, frontend/src/components/Button.tsx, frontend/src/components/Navbar.tsx, frontend/src/pages/DashboardPage.tsx, frontend/src/pages/Events.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/Rooms.tsx, frontend/src/pages/Users.tsx
=> feat: create users, rooms, events pages

frontend/src/App.tsx, frontend/src/pages/ForgotPasswordPage.tsx, frontend/src/pages/LoginPage.tsx
=> feat: create forgot password page

backend/src/index.js, backend/src/routes/users.js
Criado as rotas capazes de validar se existe um usuario no banco por nome e por email #106
=> feat: Create validatelogin and validateemailuser

backend/README.md
=> Update Backend README

backend/src/index.js, backend/src/routes/companies.js, backend/src/routes/reservations.js, backend/src/routes/rooms.js, backend/src/routes/users.js, frontend/src/pages/EasyRoomPage.tsx
=> fix: correct database routes backend and api
